### ISSUE TITLE
Passing multiple version type flags results in an error

### ISSUE THREAD

**Issue by micahr** [Netflix/unleash#10]
When accidentally using both the `-m` and `-p` flags in one command, I got the following error:

```
foo> ツ unleash -m -p
/usr/local/lib/node_modules/unleash/index.js:132
      throw new Error('You\'re confusing me! Please don\'t pass more than one version type flag')
      ^

Error: You're confusing me! Please don't pass more than one version type flag
    at /usr/local/lib/node_modules/unleash/index.js:132:13
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/unleash/index.js:129:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
```

The error message is useful, but it should be shown to the user in a more presentable fashion.

**Comment by jameswomack** [comment]
<img width="914" alt="screenshot 2017-11-11 04 36 20" src="https://user-images.githubusercontent.com/77849/32689464-4ce20126-c69a-11e7-92f7-51daba460b1d.png">

@micahr handled this in `2.0.1`
