### ISSUE TITLE
ERR_UNHANDLED_ERROR is throwing from the box

### ISSUE THREAD

**Issue by maxkudla** [Netflix/unleash#20]
`Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])` is throwing right from the box.

node v10.15.3
npm 6.4.1
unleash@2.0.1

```
max-book:test maxkudla$ unleash --patch
[10:05:23] === UNLEASH ===
[10:05:23] Utilizing next version for changelog:  0.1.1
[10:05:23] Using repo type:  github
/Users/maxkudla/.nvm/versions/node/v10.15.3/lib/node_modules/unleash/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Undertaker.emit (events.js:178:17)
    at Undertaker.EventEmitter.emit (domain.js:441:20)
    at Object.error (/Users/maxkudla/.nvm/versions/node/v10.15.3/lib/node_modules/unleash/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/maxkudla/.nvm/versions/node/v10.15.3/lib/node_modules/unleash/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/maxkudla/.nvm/versions/node/v10.15.3/lib/node_modules/unleash/node_modules/once/once.js:25:25)
    at f (/Users/maxkudla/.nvm/versions/node/v10.15.3/lib/node_modules/unleash/node_modules/once/once.js:25:25)
    at tryCatch (/Users/maxkudla/.nvm/versions/node/v10.15.3/lib/node_modules/unleash/node_modules/async-done/index.js:24:15)
    at done (/Users/maxkudla/.nvm/versions/node/v10.15.3/lib/node_modules/unleash/node_modules/async-done/index.js:40:12)
    at Domain.onError (/Users/maxkudla/.nvm/versions/node/v10.15.3/lib/node_modules/unleash/node_modules/async-done/index.js:51:5)
    at Object.onceWrapper (events.js:277:13)

**Comment by jameswomack** [comment]
@maxkudla  Sorry you were experiencing this. There are unit tests passing for Node 10 and I'm not seeing this issue. I'm late to the game here, but maybe it was related to a corrupt changelog file or there not being a git repo in the current directory...

**Comment by jameswomack** [comment]
@maxkudla it's possible v2.0.2 in NPM will resolve your issue
https://github.com/jameswomack/unleash/commits/master
